[tool.poetry]
name = "langchain-auth0-ai"
version = "0.1.0"
description = ""
authors = ["Jose F. Romaniello <jose@okta.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openfga-sdk = "^0.8.1"
langchain = "^0.3.11"

[tool.poetry.group.test.dependencies]
pytest-randomly = "^3.15.0"
pytest-asyncio = "^0.25.0"
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
